apiVersion: v1
kind: Service
metadata:
  name: ros2-novnc
  namespace: lokesh-ros2-demo
  labels:
    app: ros2-sim
spec:
  selector:
    app: ros2-sim
  ports:
    - name: novnc
      port: 6080
      targetPort: 6080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ros2-web
  namespace: lokesh-ros2-demo
  labels:
    app: ros2-sim
spec:
  selector:
    app: ros2-sim
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
